# Generated by Django 2.1.dev20171201011528 on 2017-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='direction',
            field=models.TextField(max_length=20),
        ),
    ]
